// This file is generated by Tools/Reflection/generate_reflection.ps1.
// Do not edit by hand.

#include <Engine/Foundation/Reflection/CalyxObjectRegistry.generated.h>

#include <Engine/Objects/3D/Actor/Registry/SceneObjectRegistry.h>

#include <memory>
#include <utility>

#include <Engine/Objects/3D/Actor/BaseGameObject.h>
#include <Engine/Objects/Event/Camera/CameraEventObject.h>
#include <Game/3D/Actor/DemoPlayer/DemoPlayer.h>
#include <Engine/Objects/3D/Actor/SplineDeformObject.h>
#include <Game/3D/Actor/DemoPlayer/Weapon/Weapon.h>

namespace CalyxEngine {
	void RegisterGeneratedSceneObjects() {
		{
			SceneObjectClassDesc desc;
			desc.typeName = "BaseGameObject";
			desc.displayName = "Mesh Object";
			desc.objectType = ObjectType::Actor;
			desc.iconPath = "UI/Tool/cube.dds";
			desc.placeable = true;
			desc.prefabEditable = false;
			desc.prefabRoot = false;
			desc.ctor = std::make_unique<SceneCtor<BaseGameObject>>();
			SceneObjectRegistry::Get().Register(std::move(desc));
		}

		{
			SceneObjectClassDesc desc;
			desc.typeName = "CameraEventObject";
			desc.displayName = "Camera Event";
			desc.objectType = ObjectType::Event;
			desc.iconPath = "UI/Tool/event.png";
			desc.placeable = true;
			desc.prefabEditable = false;
			desc.prefabRoot = false;
			desc.ctor = std::make_unique<SceneCtor<CameraEventObject>>();
			SceneObjectRegistry::Get().Register(std::move(desc));
		}

		{
			SceneObjectClassDesc desc;
			desc.typeName = "DemoPlayer";
			desc.displayName = "Demo Player";
			desc.objectType = ObjectType::Actor;
			desc.iconPath = "UI/Tool/cube.dds";
			desc.placeable = true;
			desc.prefabEditable = false;
			desc.prefabRoot = false;
			desc.ctor = std::make_unique<SceneCtor<DemoPlayer>>();
			SceneObjectRegistry::Get().Register(std::move(desc));
		}

		{
			SceneObjectClassDesc desc;
			desc.typeName = "SplineDeformObject";
			desc.displayName = "Spline Wall Deform";
			desc.objectType = ObjectType::Actor;
			desc.iconPath = "UI/Tool/cylinder.dds";
			desc.placeable = true;
			desc.prefabEditable = false;
			desc.prefabRoot = false;
			desc.ctor = std::make_unique<SceneCtor<SplineDeformObject>>();
			SceneObjectRegistry::Get().Register(std::move(desc));
		}

		{
			SceneObjectClassDesc desc;
			desc.typeName = "Weapon";
			desc.displayName = "Weapon";
			desc.objectType = ObjectType::Actor;
			desc.iconPath = "UI/Tool/event.png";
			desc.placeable = true;
			desc.prefabEditable = false;
			desc.prefabRoot = false;
			desc.ctor = std::make_unique<SceneCtor<Weapon>>();
			SceneObjectRegistry::Get().Register(std::move(desc));
		}
	}
}